[project]
name = "hello"
version = "0.1.0"
description = "An example Flask app running in Docker."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "alembic==1.17.2",
  "celery==5.5.3",
  "flask==3.1.2",
  "flask-db==0.4.1",
  "flask-debugtoolbar==0.16.0",
  "flask-secrets==0.1.0",
  "flask-sqlalchemy==3.1.1",
  "flask-static-digest==0.4.1",
  "gunicorn==23.0.0",
  "jinja2==3.1.6",
  "psycopg==3.2.12",
  "pytest==9.0.1",
  "pytest-cov==7.0.0",
  "redis==7.0.1",
  "ruff==0.14.5",
  "setuptools==80.9.0",
  "sqlalchemy==2.0.44",
  "sqlalchemy-utils==0.42.0",
  "werkzeug==3.1.3",
]

[tool.ruff]
line-length = 79

[tool.ruff.lint]
extend-select = ["I", "SIM"]
